export enum AuditEventType {
  PAYMENT_CREATED = "PAYMENT_CREATED",
  PAYMENT_COMPLETED = "PAYMENT_COMPLETED",
  PAYMENT_FAILED = "PAYMENT_FAILED",

  REFUND_ISSUED = "REFUND_ISSUED",
  INVOICE_GENERATED = "INVOICE_GENERATED",
  CREDIT_PAYMENT_CREATED = "CREDIT_PAYMENT_CREATED",

  // =========================
  // PRINTING EVENTS
  // =========================
  RECEIPT_PRINTED = "RECEIPT_PRINTED",
  RECEIPT_REPRINTED = "RECEIPT_REPRINTED",
  PRINTER_FAILURE = "PRINTER_FAILURE",
  PRINT_JOB_FAILED = "PRINT_JOB_FAILED",

  // =========================
  // RETURN EVENTS (TASK 13)
  // =========================
  RETURN_REQUESTED = "RETURN_REQUESTED",
  RETURN_APPROVED = "RETURN_APPROVED",
  RETURN_COMPLETED = "RETURN_COMPLETED",

  //Expense Created

  EXPENSE_CREATED = "EXPENSE_CREATED",
}