export enum AuditEventType {
  PAYMENT_CREATED = "PAYMENT_CREATED",
  PAYMENT_COMPLETED = "PAYMENT_COMPLETED",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  REFUND_ISSUED = "REFUND_ISSUED",
  INVOICE_GENERATED = "INVOICE_GENERATED",
  CREDIT_PAYMENT_CREATED = "CREDIT_PAYMENT_CREATED",
}